"""init

Revision ID: c9b322604013
Revises: 
Create Date: 2025-06-06 07:12:06.675550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b322604013'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('meta_dia', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_id'), 'pessoas', ['id'], unique=False)
    op.create_table('consumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumos_id'), 'consumos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumos_id'), table_name='consumos')
    op.drop_table('consumos')
    op.drop_index(op.f('ix_pessoas_id'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
